function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const SUPA_URL='https://kfpdzqwtninhdkwtjruc.supabase.co',SUPA_KEY='sb_publishable_a-kAHWFg9Kv3GFVGvxIjTg_c6QlqZbB';
let currentLang=localStorage.getItem('gypsy-lang')||'en',allPosts=[],commentCounts={};
const SITE_BASE='/gypsy28-build/',POST_VERSION='20260919-direct-rest';
function localUrl(path=''){const s=String(path);if(/^https?:\/\//i.test(s))return s;if(s.startsWith(SITE_BASE))return s;return SITE_BASE+s.replace(/^\//,'');}
function setLang(lang){currentLang=lang;localStorage.setItem('gypsy-lang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-sr][data-en]').forEach(el=>{el.textContent=el.dataset[lang]||el.dataset.sr});document.querySelectorAll('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.title=lang==='en'?'Gypsy 28 Catamaran — Build Journal':'Gypsy 28 Катамаран — Дневник изградње';renderPosts();}
document.querySelectorAll('.lang-switch button').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
function mediaUrl(src=''){return src?localUrl(src):'';}
function collage(p,url,title){const imgs=[p.image,...(Array.isArray(p.gallery)?p.gallery:[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);if(!imgs.length)return '';const shown=imgs.slice(0,3);return `<a class="post-collage count-${shown.length}" href="${url}" aria-label="${esc(title)}">${shown.map((src,i)=>`<span class="collage-photo"><img src="${esc(mediaUrl(src))}" alt="${esc(title)}" loading="lazy">${i===2&&imgs.length>3?`<b class="more-photos">+${imgs.length-3}</b>`:''}</span>`).join('')}</a>`;}
function renderPosts(){const box=document.getElementById('posts');if(!box)return;if(!allPosts.length){box.innerHTML='';return;}box.innerHTML=allPosts.map(p=>{const en=currentLang==='en',title=en?(p.title_en||p.title):p.title,summary=en?(p.summary_en||p.summary):p.summary,url=SITE_BASE+'post.html?post='+encodeURIComponent(p.slug)+'&v='+POST_VERSION,n=commentCounts[p.slug]||0,comments=n?` <span class="comment-count">· ${en?'Comments':'Коментари'} (${n})</span>`:'';return `<article class="card post-card">${collage(p,url,title)}<span>${en?'JOURNAL':'DNEVNIK'}</span><h3><a href="${url}">${esc(title)}</a></h3><p>${esc(summary||'')}</p><div class="post-links"><a class="read-more" href="${url}">${en?'Read more →':'Прочитај више →'}</a>${comments}</div></article>`}).join('');}
async function rest(path){const r=await fetch(SUPA_URL+'/rest/v1/'+path,{headers:{apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY},cache:'no-store'});if(!r.ok)throw new Error('Supabase '+r.status+' '+await r.text());return r.json();}
async function loadCommentCounts(){try{const rows=await rest('comments?approved=eq.true&select=post_slug');commentCounts=rows.reduce((a,c)=>{if(c.post_slug)a[c.post_slug]=(a[c.post_slug]||0)+1;return a},{});renderPosts()}catch(e){console.error(e)}}
async function loadPosts(){const box=document.getElementById('posts');if(!box)return;try{const [posts,photos]=await Promise.all([rest('posts?published=eq.true&select=*&order=published_at.desc'),rest('post_photos?select=post_id,public_url,storage_path,sort_order&order=sort_order.asc')]);const by={};photos.forEach(x=>(by[x.post_id]??=[]).push(x));allPosts=posts.map(p=>{const gallery=(by[p.id]||[]).map(x=>x.public_url||(x.storage_path?SUPA_URL+'/storage/v1/object/public/gypsy28-images/'+x.storage_path:'')).filter(Boolean);return {slug:p.slug,title:p.title,title_en:p.title_en,summary:p.summary,summary_en:p.summary_en,body:p.body,body_en:p.body_en,date:p.published_at,category:p.category,category_en:p.category_en,image:p.cover_url||gallery[0]||'',gallery};});renderPosts();loadCommentCounts();}catch(e){console.error('SUPABASE LIVE LOAD FAILED',e);box.innerHTML='<p>Objave trenutno nisu dostupne. Osvežite stranicu.</p>';}}
setLang(currentLang);loadPosts();
window.OneSignalDeferred=window.OneSignalDeferred||[];const oneSignalScript=document.createElement('script');oneSignalScript.src='https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js';oneSignalScript.defer=true;document.head.appendChild(oneSignalScript);window.OneSignalDeferred.push(async function(OneSignal){await OneSignal.init({appId:'5eacf8d9-60db-4f36-aaad-fa68997c5094'});const btn=document.createElement('button');btn.type='button';btn.id='push-optin';btn.textContent='🔔 Укључи обавештења';Object.assign(btn.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:'9999',padding:'12px 16px',border:'0',borderRadius:'10px',fontWeight:'700',cursor:'pointer',boxShadow:'0 4px 18px rgba(0,0,0,.22)'});async function refresh(){const perm=Notification.permission;if(perm==='granted'){btn.style.display='none';return;}btn.style.display='block';btn.textContent=perm==='denied'?'🔕 Обавештења су блокирана':'🔔 Укључи обавештења';}btn.addEventListener('click',async()=>{if(Notification.permission==='denied'){alert('Chrome је блокирао обавештења за овај сајт. Отворите подешавања сајта у Chrome-у и дозволите Notifications.');return;}try{await OneSignal.Notifications.requestPermission();}catch(e){console.error(e)}refresh()});document.body.appendChild(btn);refresh()});