function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
const LIVE_URL='https://kfpdzqwtninhdkwtjruc.supabase.co/functions/v1/public-posts',COMMENTS_URL='https://kfpdzqwtninhdkwtjruc.supabase.co/functions/v1/public-comments';
let currentLang=localStorage.getItem('gypsy-lang')||'en',allPosts=[],commentCounts={};const SITE_BASE='/gypsy28-build/',POST_VERSION='20260919-live-comments';
function localUrl(path=''){const s=String(path);if(/^https?:\/\//i.test(s))return s;if(s.startsWith(SITE_BASE))return s;return SITE_BASE+s.replace(/^\//,'');}
function setLang(lang){currentLang=lang;localStorage.setItem('gypsy-lang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-sr][data-en]').forEach(el=>{el.textContent=el.dataset[lang]||el.dataset.sr});document.querySelectorAll('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.title=lang==='en'?'Gypsy 28 Catamaran — Build Journal':'Gypsy 28 Катамаран — Дневник изградње';renderPosts();}
document.querySelectorAll('.lang-switch button').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
function mediaUrl(src=''){return src?localUrl(src):'';}
function collage(p,url,title){const imgs=[p.image,...(Array.isArray(p.gallery)?p.gallery:[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);if(!imgs.length)return '';const shown=imgs.slice(0,3);return `<a class="post-collage count-${shown.length}" href="${url}" aria-label="${esc(title)}">${shown.map((src,i)=>`<span class="collage-photo"><img src="${esc(mediaUrl(src))}" alt="${esc(title)}" loading="lazy">${i===2&&imgs.length>3?`<b class="more-photos">+${imgs.length-3}</b>`:''}</span>`).join('')}</a>`;}
function renderPosts(){const box=document.getElementById('posts');if(!box)return;if(!allPosts.length){box.innerHTML='';return;}box.innerHTML=allPosts.map(p=>{const en=currentLang==='en',title=en?(p.title_en||p.title):p.title,summary=en?(p.summary_en||p.summary):p.summary,url=SITE_BASE+'post.html?post='+encodeURIComponent(p.slug)+'&v='+POST_VERSION,n=commentCounts[p.slug]||0,comments=n?` <span class="comment-count">· ${en?'Comments':'Коментари'} (${n})</span>`:'';return `<article class="card post-card">${collage(p,url,title)}<span>${en?'JOURNAL':'DNEVNIK'}</span><h3><a href="${url}">${esc(title)}</a></h3><p>${esc(summary||'')}</p><div class="post-links"><a class="read-more" href="${url}">${en?'Read more →':'Прочитај више →'}</a>${comments}</div></article>`}).join('');}
async function loadCommentCounts(){commentCounts={};await Promise.all(allPosts.map(async p=>{try{const r=await fetch(COMMENTS_URL+'?post_slug='+encodeURIComponent(p.slug)+'&t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const rows=await r.json();if(Array.isArray(rows))commentCounts[p.slug]=rows.length}catch(e){console.error('COMMENT COUNT FAILED',p.slug,e)}}));renderPosts();}
async function loadPosts(){const box=document.getElementById('posts');if(!box)return;try{const r=await fetch(LIVE_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Live posts '+r.status+' '+await r.text());const data=await r.json();if(!Array.isArray(data))throw new Error('Invalid live posts payload');allPosts=data;renderPosts();loadCommentCounts();}catch(e){console.error('LIVE POSTS FAILED',e);box.innerHTML='<p>Objave trenutno nisu dostupne. Osvežite stranicu.</p>';}}
setLang(currentLang);loadPosts();