function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let currentLang=localStorage.getItem('gypsy-lang')||'sr';
let allPosts=[];
let activeCategory='all';
const categories=[['all','Све','All'],['Izgradnja','Изградња','Construction'],['Materijali','Материјали','Materials'],['Izmene projekta','Измене пројекта','Project changes'],['Troškovi','Трошкови','Costs'],['Galerija','Галерија','Gallery']];
function setLang(lang){currentLang=lang;localStorage.setItem('gypsy-lang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-sr][data-en]').forEach(el=>{el.textContent=el.dataset[lang]||el.dataset.sr});document.querySelectorAll('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.title=lang==='en'?'Gypsy 28 Build — Build Journal':'Gypsy 28 Build — Dnevnik izgradnje';renderFilters();renderPosts();}
document.querySelectorAll('.lang-switch button').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
function collage(p,url,title){const imgs=[p.image,...(Array.isArray(p.gallery)?p.gallery:[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);if(!imgs.length)return '';const shown=imgs.slice(0,3);const cls=`post-collage count-${shown.length}`;return `<a class="${cls}" href="${url}" aria-label="${esc(title)}">${shown.map((src,i)=>`<span class="collage-photo"><img src="${esc(src)}" alt="${esc(title)}" loading="lazy">${i===2&&imgs.length>3?`<b class="more-photos">+${imgs.length-3}</b>`:''}</span>`).join('')}</a>`;}
function renderFilters(){const box=document.getElementById('post-filters');if(!box)return;box.innerHTML=categories.map(([key,sr,en])=>`<button type="button" data-category="${esc(key)}" class="${activeCategory===key?'active':''}">${currentLang==='en'?en:sr}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;renderFilters();renderPosts();}));}
function renderPosts(){const box=document.getElementById('posts');if(!box||!allPosts.length)return;const posts=activeCategory==='all'?allPosts:allPosts.filter(p=>p.category===activeCategory);if(!posts.length){box.innerHTML=`<p class="no-posts">${currentLang==='en'?'No posts in this category yet.':'Још нема објава у овој категорији.'}</p>`;return;}box.innerHTML=posts.map(p=>{const en=currentLang==='en',title=en?(p.title_en||p.title):p.title,category=en?(p.category_en||p.category):p.category,summary=en?(p.summary_en||p.summary):p.summary,url=`/post.html?post=${encodeURIComponent(p.slug)}`;return `<article class="card post-card">${collage(p,url,title)}<span>${esc(category||(en?'JOURNAL':'DNEVNIK'))}</span><h3><a href="${url}">${esc(title)}</a></h3><p>${esc(summary||'')}</p><a class="read-more" href="${url}">${en?'Read more →':'Прочитај више →'}</a></article>`}).join('');}
async function loadPosts(){const box=document.getElementById('posts');if(!box)return;try{const r=await fetch('/content/posts/index.json',{cache:'no-store'});if(!r.ok)return;allPosts=await r.json();renderFilters();renderPosts();}catch(e){console.error(e)}}
setLang(currentLang);loadPosts();
