backend:
  name: github
  repo: goranrakocevicns-cyber/gypsy28-build
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"
locale: "sr"

collections:
  - name: "posts"
    label: "Objave"
    label_singular: "Objava"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - label: "Kategorija"
        name: "category"
        widget: "select"
        options: ["Izgradnja", "Materijali", "Izmene projekta", "Troškovi", "Galerija"]
      - { label: "Naslovna fotografija", name: "image", widget: "image", required: false }
      - { label: "Tekst", name: "body", widget: "markdown" }
