backend:
  name: turbo-github
  turbo_site_id: 4b527bfc-e318-46da-adc5-11fda1a5d3f1
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"
locale: "sr"

collections:
  - name: "posts"
    label: "Objave"
    label_singular: "Objava"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Naslov (SR)", name: "title", widget: "string" }
      - { label: "Naslov (EN)", name: "title_en", widget: "string", required: false }
      - { label: "Datum", name: "date", widget: "datetime" }
      - label: "Fotografije objave"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        summary: "Fotografija {{index}}"
        field:
          label: "Fotografija"
          name: "image"
          widget: "image"
          choose_url: false
          media_library:
            config:
              multiple: false
      - { label: "Tekst (SR)", name: "body", widget: "markdown" }
      - { label: "Kratak opis (EN)", name: "summary_en", widget: "text", required: false }
